### ISSUE TITLE
gabibbo97/dex chart: Invalid client_id ("example-app")

### ISSUE THREAD

**Issue by sagarpatke** [gabibbo97/charts#36]

**Comment by gabibbo97** [comment]
More details?

**Comment by xakraz** [comment]
I think I have found the issue ...

It is due to the inconsciente way of usage of ENV vars in Dex config:

Main discussions about this is: 
* https://github.com/dexidp/dex/issues/1099

Currently there are 3 implementations:
* For Connectors: https://dexidp.io/docs/connectors/github/
* For StaticClients: https://github.com/dexidp/dex/pull/1664
* For StaticPasswords: https://github.com/dexidp/dex/pull/1601

So, when in the templates @gabibbo97 you generate the Dex Config and use ENV vars for `clientId` and `clientSecret`, it does not work...

In the end, Dex complains about an unknown client_id

**Comment by xakraz** [comment]
So in the end, if we want to keep using ENV vars for StaticClients, we have to:
1. Remove the `$` leading the ENV VAR name
2. Replace the key `secret` by `secretEnv`

**Comment by xakraz** [comment]
Seems also mentioned here: https://github.com/helm/charts/issues/22427

**Comment by gabibbo97** [comment]
Thanks for the report!
I'll take a look, probably this has been changed because I remember it working in one of the first iterations of the chart.
I'll hit you up with a diff as soon as this nightmareish work gives me a break
